spring:
  application:
    name: Notifyr

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/notifyr_db?TimeZone=Asia/Kolkata
    username: notifyr_user
    password:  notifyr_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: notifyr_user
    password: notifyr_password

notification:
  simulate-failure-rate: 0.1
  api-key: my-secret-api-key
  queue:
    name: notification.queue
  exchange:
    name: notification.exchange
  routing-key: notification.route
  retry:
    exchange: notification.retry.exchange
    queue-30s: notification.retry.30s
    queue-2m: notification.retry.2m
    queue-5m: notification.retry.5m
    routing-key-30s: retry.30s
    routing-key-2m: retry.2m
    routing-key-5m: retry.5m
    ttl-30s: 5000
    ttl-2m: 10000
    ttl-5m: 15000
  dlq:
    exchange: notification.dlq.exchange
    queue: notification.dlq
    routing-key: dlq.route

server:
  port: 8080
